language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=django==1.4.5
  - DJANGO=django==1.5
  - DJANGO=https://github.com/django/django/archive/master.zip

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO=django==1.4.5
  - python: "3.2"
    env: DJANGO=django==1.4.5
install:
  - "pip install $DJANGO coverage==3.6 --use-mirrors"
script:
  - coverage run --source=polymorphic runtests.py
  - coverage report -m
after_success:
  - "pip install coveralls==0.1.1 --use-mirrors"
  - coveralls
branches:
  only:
    - master
