sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOXENV="django14-mysql"
  - TOXENV="django14-postgres"
  - TOXENV="django14-sqlite"
  - TOXENV="django15-mysql"
  - TOXENV="django15-postgres"
  - TOXENV="django15-sqlite"
  - TOXENV="django16-mysql"
  - TOXENV="django16-postgres"
  - TOXENV="django16-sqlite"
  - TOXENV="django17-mysql"
  - TOXENV="django17-postgres"
  - TOXENV="django17-sqlite"
  - TOXENV="django18-mysql"
  - TOXENV="django18-postgres"
  - TOXENV="django18-sqlite"
  - TOXENV="django19-mysql"
  - TOXENV="django19-postgres"
  - TOXENV="django19-sqlite"
  - TOXENV="django110-mysql"
  - TOXENV="django110-postgres"
  - TOXENV="django110-sqlite"
  - TOXENV="django111-mysql"
  - TOXENV="django111-postgres"
  - TOXENV="django111-sqlite"
  - TOXENV="djangodev-mysql"
  - TOXENV="djangodev-postgres"
  - TOXENV="djangodev-sqlite"

matrix:
  fast_finish: true
  exclude:
    - python: "3.6"
      env: TOXENV="django14-mysql"
    - python: "3.6"
      env: TOXENV="django14-postgres"
    - python: "3.6"
      env: TOXENV="django14-sqlite"
    - python: "3.6"
      env: TOXENV="django15-mysql"
    - python: "3.6"
      env: TOXENV="django15-postgres"
    - python: "3.6"
      env: TOXENV="django15-sqlite"
    - python: "3.6"
      env: TOXENV="django16-mysql"
    - python: "3.6"
      env: TOXENV="django16-postgres"
    - python: "3.6"
      env: TOXENV="django16-sqlite"
    - python: "3.6"
      env: TOXENV="django17-mysql"
    - python: "3.6"
      env: TOXENV="django17-postgres"
    - python: "3.6"
      env: TOXENV="django17-sqlite"
    - python: "3.6"
      env: TOXENV="django18-mysql"
    - python: "3.6"
      env: TOXENV="django18-postgres"
    - python: "3.6"
      env: TOXENV="django18-sqlite"
    - python: "3.6"
      env: TOXENV="django19-mysql"
    - python: "3.6"
      env: TOXENV="django19-postgres"
    - python: "3.6"
      env: TOXENV="django19-sqlite"
    - python: "3.6"
      env: TOXENV="django110-mysql"
    - python: "3.6"
      env: TOXENV="django110-postgres"
    - python: "3.6"
      env: TOXENV="django110-sqlite"

    - python: "3.5"
      env: TOXENV="django14-mysql"
    - python: "3.5"
      env: TOXENV="django14-postgres"
    - python: "3.5"
      env: TOXENV="django14-sqlite"
    - python: "3.5"
      env: TOXENV="django15-mysql"
    - python: "3.5"
      env: TOXENV="django15-postgres"
    - python: "3.5"
      env: TOXENV="django15-sqlite"
    - python: "3.5"
      env: TOXENV="django16-mysql"
    - python: "3.5"
      env: TOXENV="django16-postgres"
    - python: "3.5"
      env: TOXENV="django16-sqlite"
    - python: "3.5"
      env: TOXENV="django17-mysql"
    - python: "3.5"
      env: TOXENV="django17-postgres"
    - python: "3.5"
      env: TOXENV="django17-sqlite"

    - python: "3.4"
      env: TOXENV="django14-mysql"
    - python: "3.4"
      env: TOXENV="django14-postgres"
    - python: "3.4"
      env: TOXENV="django14-sqlite"
    - python: "3.4"
      env: TOXENV="django19-mysql"
    - python: "3.4"
      env: TOXENV="django19-postgres"
    - python: "3.4"
      env: TOXENV="django19-sqlite"
    - python: "3.4"
      env: TOXENV="django110-mysql"
    - python: "3.4"
      env: TOXENV="django110-postgres"
    - python: "3.4"
      env: TOXENV="django110-sqlite"
    - python: "3.4"
      env: TOXENV="django111-mysql"
    - python: "3.4"
      env: TOXENV="django111-postgres"
    - python: "3.4"
      env: TOXENV="django111-sqlite"

    - python: "3.3"
      env: TOXENV="django14-mysql"
    - python: "3.3"
      env: TOXENV="django14-postgres"
    - python: "3.3"
      env: TOXENV="django14-sqlite"
    - python: "3.3"
      env: TOXENV="django19-mysql"
    - python: "3.3"
      env: TOXENV="django19-postgres"
    - python: "3.3"
      env: TOXENV="django19-sqlite"
    - python: "3.3"
      env: TOXENV="django110-mysql"
    - python: "3.3"
      env: TOXENV="django110-postgres"
    - python: "3.3"
      env: TOXENV="django110-sqlite"
    - python: "3.3"
      env: TOXENV="django111-mysql"
    - python: "3.3"
      env: TOXENV="django111-postgres"
    - python: "3.3"
      env: TOXENV="django111-sqlite"
    - python: "3.3"
      env: TOXENV="djangodev-mysql"
    - python: "3.3"
      env: TOXENV="djangodev-postgres"
    - python: "3.3"
      env: TOXENV="djangodev-sqlite"

    - python: "3.2"
      env: TOXENV="django14-mysql"
    - python: "3.2"
      env: TOXENV="django14-postgres"
    - python: "3.2"
      env: TOXENV="django14-sqlite"
    - python: "3.2"
      env: TOXENV="django19-mysql"
    - python: "3.2"
      env: TOXENV="django19-postgres"
    - python: "3.2"
      env: TOXENV="django19-sqlite"
    - python: "3.2"
      env: TOXENV="django110-mysql"
    - python: "3.2"
      env: TOXENV="django110-postgres"
    - python: "3.2"
      env: TOXENV="django110-sqlite"
    - python: "3.2"
      env: TOXENV="django111-mysql"
    - python: "3.2"
      env: TOXENV="django111-postgres"
    - python: "3.2"
      env: TOXENV="django111-sqlite"
    - python: "3.2"
      env: TOXENV="djangodev-mysql"
    - python: "3.2"
      env: TOXENV="djangodev-postgres"
    - python: "3.2"
      env: TOXENV="djangodev-sqlite"

    - python: "2.7"
      env: TOXENV="djangodev"

    - python: "2.6"
      env: TOXENV="django17-mysql"
    - python: "2.6"
      env: TOXENV="django17-postgres"
    - python: "2.6"
      env: TOXENV="django17-sqlite"
    - python: "2.6"
      env: TOXENV="django18-mysql"
    - python: "2.6"
      env: TOXENV="django18-postgres"
    - python: "2.6"
      env: TOXENV="django18-sqlite"
    - python: "2.6"
      env: TOXENV="django19-mysql"
    - python: "2.6"
      env: TOXENV="django19-postgres"
    - python: "2.6"
      env: TOXENV="django19-sqlite"
    - python: "2.6"
      env: TOXENV="django110-mysql"
    - python: "2.6"
      env: TOXENV="django110-postgres"
    - python: "2.6"
      env: TOXENV="django110-sqlite"
    - python: "2.6"
      env: TOXENV="django111-mysql"
    - python: "2.6"
      env: TOXENV="django111-postgres"
    - python: "2.6"
      env: TOXENV="django111-sqlite"
    - python: "2.6"
      env: TOXENV="djangodev-mysql"
    - python: "2.6"
      env: TOXENV="djangodev-postgres"
    - python: "2.6"
      env: TOXENV="djangodev-sqlite"

  allow_failures:
    - env: TOXENV="djangodev-mysql"
    - env: TOXENV="djangodev-postgres"
    - env: TOXENV="djangodev-sqlite"

before_install:
  - pip install codecov coverage==3.6 tox
  - if [[ $TOXENV == *mysql ]]; then mysql -e 'CREATE DATABASE polymorphic; CREATE DATABASE polymorphic2;'; fi
  - if [[ $TOXENV == *postgres ]]; then psql -c 'CREATE DATABASE polymorphic;' -U postgres; fi
  - if [[ $TOXENV == *postgres ]]; then psql -c 'CREATE DATABASE polymorphic2;' -U postgres; fi

script:
  - tox

after_success:
- coverage xml -i
- codecov

branches:
  only:
    - master
